title: ExaWorks
description: "ExaWorks: Exascale Workflows Project"

markdown: kramdown

baseurl: "" # the subpath of your site, e.g. /blog

collections: 
  people:
    output: false

plugins:
  - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
  - jekyll-feed       # Adds feed to the website at /feed.xml
  - jekyll-seo-tag    # Adds all the important SEO meta tags by default.

exclude:
  - .jekyll-cache
  - README.md
  - LICENSE

# Build settings
#markdown: kramdown
#theme: minima
